### ISSUE TITLE
vo=gpu in ~/.config/mpv/mpv.conf shows the video in a window instead of background

### ISSUE THREAD

**Issue by Lahvuun** [GhostNaN/mpvpaper#10]
Same if I pass it manually: `mpvpaper -o "--vo=gpu" DP-3 asdf.mp4`

**Comment by GhostNaN** [comment]
That's correct as mpvpaper uses the "libmpv" vo. I don't believe there is a way around this. If you wish to have GPU accelerated video I would use "hwdec=auto". And if you have to, specify "vo=libmpv" to override your config settings.

**Comment by Lahvuun** [comment]
Indeed, invoking mpvpaper with `-o "--vo=libmpv"` works. Thank you for the answer.

Do you think mpvpaper could force `libmpv` as the `vo` somehow? The mpv wiki states that you should use `vo_gpu`: https://github.com/mpv-player/mpv/wiki/Which-VO-should-I-use so I'm probably not the last person you'll see with this issue.

**Comment by GhostNaN** [comment]
I think so:
https://github.com/GhostNaN/mpvpaper/commit/d8e5f2373b7da3de77d89f6b28fe2bb09ec2b8a7

**Comment by Lahvuun** [comment]
Works well for me. Thank you again!

**Comment by trinitronx** [comment]
> I don't believe there is a way around this.

@GhostNaN, @Lahvuun: Good news everyone! ☝️👨‍🔬

I've managed to find a way around this.  At least, to support a custom default `-vo` option in `mpv.conf` without overriding `mpvpaper`'s need for `-vo=libmpv`.  In my case, I had `vo = gpu-next` in the default section of `mpv.conf`, along with some other options that did not make sense for `mpvpaper`, but otherwise were desirable for default `mpv` settings when run normally.  One of these was using the `mpris.so` plugin which integrates `mpv` with `playerctl` and [Manjaro Sway Edition's `waybar` module: `custom/playerctl`][3].  With the `mpris.so` plugin loaded by default, the play/pause `waybar` widget would play & pause the `mpvpaper` wallpaper video, and prevent any normal "_interactive_" `mpv` instance from working with it.  That wasn't ideal, so I worked on finding a solution.  This method should work for any profile-specific settings for `mpvpaper` and "_interactive_" `mpv` instances.

In order to work around this, I used [`mpv` profiles][1] and the [Conditional auto profiles][2] feature in `mpv.conf`:

```
# https://mpv.io/manual/master/

# Default settings here for all profiles
hwdec = vaapi
screenshot-directory = ~/Screenshots

# Settings for mpvpaper
# non-interactive mode: Turn off unnecessary features
[mpvpaper]
profile-desc="Minimal mpvpaper video desktop background"
vo=libmpv
loop=inf
terminal=no
mute=yes
load-scripts=no
osc=no
load-stats-overlay=no
load-osd-console=no
load-auto-profiles=yes
load-select=no

# Default mpv settings here for "interactive" mode
# e.g. mpv launched as a normal window without -vo=libmpv
[interactive]
profile-cond=not current_vo:find('libmpv')
script = /etc/mpv/scripts/mpris.so
vo = gpu-next

```

With this configuration, it works when starting `mpvpaper` with `include=path/to/mpv.conf profile=mpvpaper`.  The reason that the extra `include` flag is needed is due to the way that `mpvpaper` writes out a temporary `mpv.conf` file before starting `mpv` with that temporary config.  This allows us to include our user config that defines the `mpvpaper` profile.

A full example `sway` config to launch `mpvpaper` in this way might be:

```
exec mpvpaper --mpv-options "include=${XDG_CONFIG_HOME}/mpv/mpv.conf profile=mpvpaper input-ipc-server=${XDG_RUNTIME_DIR}/mpvpaper-socket" '*' ${XDG_VIDEOS_DIR}/mpvpaper-desktop-backgrounds/something.mkv
```

For those curious, my [full `mpv.conf` is here][4] and my [`sway` configuration for launching `mpvpaper` is here][5]

[1]: https://mpv.io/manual/master/#profiles
[2]: https://mpv.io/manual/master/#conditional-auto-profiles
[3]: https://github.com/manjaro-sway/desktop-settings/blob/be0d2102e8b1d22c08e24a01fff09e4441cdd0dc/community/sway/usr/share/sway/templates/waybar/config.jsonc#L247-L262
[4]: https://github.com/trinitronx/dotfiles/blob/e0e95c35b6aa2b124173b61a3e101cb5d33eabca/dot_config/private_mpv/mpv.conf
[5]: https://github.com/trinitronx/dotfiles/blob/e0e95c35b6aa2b124173b61a3e101cb5d33eabca/dot_config/sway/config.d/01-mpvpaper-video-wallpaper.conf
