### ISSUE TITLE
segfault when trying to run on a HDMI monitor

### ISSUE THREAD

**Issue by hkupty** [GhostNaN/mpvpaper#16]
Hi, thanks a lot for this, it is really amazing.

I'm using it on my setup to have nice background on my login screen (w/ greetd/wlgreet).

It works flawlessly on `eDP-1` for my laptop, but when I have another screen connected (i.e. `HDMI-A-1`) I get the following output:
```
zsh: segmentation fault (core dumped)  mpvpaper -s -v -o 'no-audio loop-playlist=inf' "HDMI-A-1"
```

Doesn't really matter which flags I pass or which mp4 file I use, I always get this result.

Let me know how I can provide more info for debugging this.

Thanks in advance.

**Comment by GhostNaN** [comment]
Weird, I never had a problem using my 2nd HDMI-A-2 screen. Is this behavior also happening within sway? I tried replicating this issue, but wlgreet won't build for some reason.

It would really help if I had the line number where it failed. If you are unsure how:
1. Get valgrind
2. Build mpvpaper yourself
3. run in the build folder ```valgrind ./mpvpaper -v HDMI-A-1 /your/video/file/here```
4. Look for something like "Process terminating with default action of signal 11 (SIGSEGV): dumping core"
    It should be near the bottom.
5. Give me the terminal log from that point on (otherwise the log will be HUGE)

Thanks for reporting this issue.

**Comment by hkupty** [comment]
Sorry, this is weird. I couldn't get to reproduce it. It takes me a while because that only happened at my office's monitor, which I'm not going to frequently. I'll try again in the future and if it happens I'll debug it definitely. For the sake of not keeping this up for long, I'll close the issue and re-open if it happens again.

Have excellent holidays and an awesome 2022!

Best regards,
Henry

**Comment by GhostNaN** [comment]
Hm, It just started working? Perhaps a simple reboot fixed it for now. I myself have mpvpaper crash like once a month, with seemingly no cause. I guess computers can be weird like that. Anyways, I hope it was just a weird fluke, let me know otherwise. 

Thanks again.
