### ISSUE TITLE
Build not found mpv as dependency

### ISSUE THREAD

**Issue by Mederim** [GhostNaN/mpvpaper#18]
I use kiss linux distribution and tried to port the package to community repo but i cant build it:

```
The Meson build system
Version: 0.60.2
Source dir: /home/hellboy/mpvpaper
Build dir: /home/hellboy/mpvpaper/output
Build type: native build
Project name: mpvpaper
Project version: undefined
C compiler for the host machine: cc (gcc 11.2.0 "cc (GCC) 11.2.0")
C linker for the host machine: cc ld.bfd 2.37
Host machine cpu family: x86_64
Host machine cpu: x86_64
Library dl found: YES
Found pkg-config: /usr/bin/pkg-config (1.8.0)
Run-time dependency wayland-protocols found: YES 1.24
Run-time dependency wayland-client found: YES 1.20.0
Run-time dependency wayland-egl found: YES 18.1.0
Run-time dependency egl found: YES 21.3.1
Found CMake: /usr/bin/cmake (3.22.1)
Run-time dependency mpv found: NO (tried pkgconfig and cmake)

meson.build:9:0: ERROR: Dependency "mpv" not found, tried pkgconfig and cmake

A full log can be found at /home/hellboy/mpvpaper/output/meson-logs/meson-log.txt
```

and i have build mpv it have in the official repo you can look in here [mpv](https://github.com/kisslinux/repo/tree/master/extra/mpv)

**Comment by GhostNaN** [comment]
It looks like a meson couldn't find mpv. I'm not sure if I can do anything about that. If you built mpv yourself locally, try installing from the official repo, because mpv might be in a weird location. Or you're going to have to tell pkgconfig or cmake where to find mpv. 

Sorry if I couldn't be of any help.

**Comment by Mederim** [comment]
Meson do the search in what path? And how can i set pkgconf to search mpv?

**Comment by GhostNaN** [comment]
Use something like the LIBRARY_PATH or PKG_CONFIG_PATH env variable. It's probably easier if you can find where or even if you have a "mpv.pc" pkgconf file. For example my mpv.pc is at "/usr/lib/pkgconfig/mpv.pc" so I would use something like this:
```PKG_CONFIG_PATH=/usr/lib/pkgconfig/```
Your package manager should of installed this config file for you, otherwise I'm not sure how to obtain one.

**Comment by Mederim** [comment]
Libmpv is needed for this package?

**Comment by GhostNaN** [comment]
Yes
https://github.com/GhostNaN/mpvpaper/blob/ff398978941f95b5d1e424e26e8b7498e8176205/src/main.c#L19-L20

**Comment by Mederim** [comment]
Maybe this is the problem, i not have libmpv build. And mpv no needed it to work well.

**Comment by FFFluoride** [comment]
I got it to work when I installed ```libmpv-dev``` so I think you should maybe update your build scripts (or whatever) to reflect this.
