### ISSUE TITLE
GPU Memory Leak ??

### ISSUE THREAD

**Issue by dmadisetti** [GhostNaN/mpvpaper#21]
Using mpvpaper with Hyprland and a 1660Ti. Typically mpvpaer will idle at 200MB of GPU memory, but occasionally that value will balloon to like 6GB causing other programs to crash. Could be a WM issue? Idk, I don't know anything about display programs

**Comment by GhostNaN** [comment]
What are your terminal args?
How long does this ballooning take to occur?

This might not be a mpvpaper problem necessarily. 
The only time mpvpaper is really doing anything direct with the GPU is when EGL is initialized and when the EGL buffers are swapped.
The rest is given and taken care of by mpv and the Wayland compositor.

It could be a WM issue. The only way to know for sure is to use something like Sway and see if the same issue arises.
It might also be a problem with mpv. Again, you would have to check if that problem happens there as well.

If you have the time, report back your findings. I would appreciate it.

**Comment by dmadisetti** [comment]
![20220727_13h25m38s_grim](https://user-images.githubusercontent.com/2689338/181310892-512b786d-a2ad-4c61-b7f6-afa664033525.png)

Hmm, multiple instances spawning is likely the compositor. I think the issue is when I change compositor config values. So that would not be a mpvpaper issue. It might not even be a WM problem and a user config issue.

But even so, mpv should be idling at like 200MB? So something is growing.

Invoking command is: `mpvpaper -spf -o "--loop --panscan=1" HDMI-A-2 ~/keybase/private/dmadisetti/backgrounds/space/clips`

Let me know if there are any logs I can pull or whether you think this is likely not a mpvpaper issue

**Comment by GhostNaN** [comment]
2 things:

The flags ```-s``` and ```-p``` can't be used together. 
It will only end up being the last one, in this case ```-p```.
I would just advise to use  only ```-s``` so you save RAM/VRAM usage if mpvpaper is not seen.
Refer to here as to how that works:
https://github.com/GhostNaN/mpvpaper/blob/666f4c9a8fdc7e921073366fc939c335318f723f/src/main.c#L881-L888

And second, it could be possible that there are indeed multiple instances running of mpvpaper.
I use ```nvtop``` to measure VRAM usage so i don't really know how ```nvidia-smi``` behaves.
Feel free to kill some processes to so see if it's just 1 or multiple instances running in the background.
You can tell if it's multiple instances if you kill a process just to find another video is playing in the background.
If it's actually multiple instances running try not using the ```-s``` flag all together. 
Because the ```-s``` flag should kill the current process if mpvpaper isn't see, then proceed to reboot mpvpaper with the help of ```mpvpaper-holder``` when it can be seen again.
So maybe it's not killing the current process and just creating new ones.
It should be killing it here:
https://github.com/GhostNaN/mpvpaper/blob/666f4c9a8fdc7e921073366fc939c335318f723f/src/main.c#L213-L219
If that made no sense look at the man page under "NOTES".
Also add the ```-v``` flag to see if any funny/error messages pop up.

If it turns out if it really is just 1 instance mpvpaper running and there is no other videos playing.
Then it's probably not mpvpaper's fault and I'm frankly not sure how to proceed.

Sorry for the long comment I hope that was informative.

**Comment by dmadisetti** [comment]
That was informative. I was able to force memory growth by switching workspaces and swapping between full screen.

(this is using the `-sf` flag, but I will play with `-pf` too)

![20220728_00h43m12s_grim](https://user-images.githubusercontent.com/2689338/181422566-f231c48c-91f4-40a5-8cf0-d9a520419d4e.png)

Interestingly nvtop just shows the expected 178MB...

![20220728_00h47m11s_grim](https://user-images.githubusercontent.com/2689338/181422760-bd5caf36-124d-4d36-81a3-b72e52cc9932.png)

I am going to log with -v and dump everything into a file, play around with it and report back

**Comment by dmadisetti** [comment]
I haven't seen this in awhile- so probably a Hyprland issue. Will close to reduce clutter. Current facing the same problems as #44, happy to provide debugging there too

**Comment by JKing6250** [comment]
I don't know how I can help with this, but I'm experiencing the same issue. I would wager it has more to do with mpv than mpvpaper, but when first initialized "mpvpaper -o --loop DP-1 ~/Videos/LiveWallpaperleft/left_EyesofEnigma.mp4 & mpvpaper -o --loop DP-3 ~/Videos/LiveWallpaperright/right_EyesofEnigma.mp4" plays as intended, but as it loops it seems to be ballooning in RAM. I leave my desktop on about 99% of the time, so naturally my logs indicate this behavior continues until the oom killer tries everything but mpv and ultimately the system hard freezes. I'll happily contribute any diagnostic data I can. Love this project and would like to see it succeed. If this belongs somewhere else please let me know.
