### ISSUE TITLE
Blurred background when using fractional scaling.

### ISSUE THREAD

**Issue by DHWIDSA** [GhostNaN/mpvpaper#24]
If you use a scaling between 1-2 in the sway's settings, the background will become blurred.
## How to Reproduce：
Set scale 1.5 in sway's monitor settings.
Then
```
mpv wallpaper xxx
```
The background will not be blurred if the scale 1 setting is used.

**Comment by GhostNaN** [comment]
Should be fixed as of this commit: https://github.com/GhostNaN/mpvpaper/commit/f65700a3ecc9ecd8ca501e18a807ee18845f9441
Let me know. It seemed better on my pc.

Turned out someone had done this already, but the never made a pull request: https://github.com/y-fujii/mpvpaper/commit/a13273d4d53ec3ef576edbc5e8897d173a49e704

**Comment by DHWIDSA** [comment]
> Should be fixed as of this commit: [f65700a](https://github.com/GhostNaN/mpvpaper/commit/f65700a3ecc9ecd8ca501e18a807ee18845f9441) Let me know. It seemed better on my pc.
> 
> Turned out someone had done this already, but the never made a pull request: [y-fujii@a13273d](https://github.com/y-fujii/mpvpaper/commit/a13273d4d53ec3ef576edbc5e8897d173a49e704)

**Comment by DHWIDSA** [comment]
Thanks, the problem has been well solved and the wallpaper is now as clear on screens with DPI scaling as it is without it. I suggest to publish a new release version.
