### ISSUE TITLE
video starting as a window

### ISSUE THREAD

**Issue by 9JH1** [GhostNaN/mpvpaper#61]
when i run the command ```mpv DP-2 video.mp4``` the video opens as a window instead of as a background,  im running arch linux with i3

**Comment by GhostNaN** [comment]
> im running arch linux with i3

That's a X11 compositor.

"**mpvpaper** is a wallpaper program for **wlroots** based **wayland** compositors, such as sway."

If you want you could use Sway as a drop in replacement for i3.
https://wiki.archlinux.org/title/Sway

I would also like to point to another project if you want to stay on i3
https://github.com/ujjwal96/xwinwrap

Otherwise mpvpaper will **never** ever support X11. 
As it would mean going through the hell that is X11 code.
