### ISSUE TITLE
Nvidia blackscreen/window and not background

### ISSUE THREAD

**Issue by Rodrigo-Matuz** [GhostNaN/mpvpaper#70]
hyprland + wayland + Nvidia-dkms (1050 Ti) + arch (btw) 

I already tried the [f65700a](https://github.com/GhostNaN/mpvpaper/commit/f65700a3ecc9ecd8ca501e18a807ee18845f9441) branch but then I get the video  displayed as window 

(which I did tried [hyprwinwrap)](https://github.com/hyprwm/hyprland-plugins/tree/main/hyprwinwrap) plugin to get the window and set as background but not working: [I've set an issue there too](https://github.com/hyprwm/hyprland-plugins/issues/151)

for the main branch I get black screen
some commands I tried 
![image](https://github.com/GhostNaN/mpvpaper/assets/109036200/f65791ec-6556-474f-9bc3-61748aaf6105)

Logs:
![image](https://github.com/GhostNaN/mpvpaper/assets/109036200/848d8088-e0da-43c4-bbb2-dcfc744c09da)
[output.txt](https://github.com/GhostNaN/mpvpaper/files/15078482/output.txt)

Note: I'm wondering if a animated waifu wallpaper is worth this much effort lol

**Comment by GhostNaN** [comment]
> I already tried the f65700a branch but then I get the video displayed as window

Yes, thanks to the mpv 0.38 update it made "libmpv" not the default VO which was fixed here: https://github.com/GhostNaN/mpvpaper/commit/8fe75d88505b0fd857f8efea3750586ae5ffc096
And that old commit is starting to rot because of that.

For now you could use that old commit but just set the VO manually to "libmpv" like so:
```mpvpaper -o "--vo=libmpv" HDMI-A-1 ~/Pictures/wallpaper.mp4```

But I must admit it's getting a bit silly with the workarounds here.
I'll consider adding back the old render loop as an option.

> for the main branch I get black screen
> OpenGL error INVALID_OPERATION.

Yep, same old Nvidia proprietary driver issue.
I don't have a Nvidia GPU to properly dive into making a fix.
As for the OpenGL error, I don't know what is going on there. 
I tried looking into it here: https://github.com/GhostNaN/mpvpaper/issues/54

>  ( I did tried hyprwinwrap) plugin to get the window and set as background but not working: I've set an issue there too

I would close that issue there, as it's not their fault.

Last thing, I have a little theory I would like you to try for me.
The problems arose when the EGL initalization was changed here: https://github.com/GhostNaN/mpvpaper/commit/0475df808f302c11c2d69ad1bd32fd2acb9cf2cf
But I found the issue to be the ```eglMakeCurrent(egl_display, EGL_NO_SURFACE, EGL_NO_SURFACE, egl_context)```
That was fixed by adding ```glDrawBuffer(GL_BACK)``` afterward.
So, I'm wondering if this problem is just with the EGL init or it's the actual render loop as well.
Please try this patch version of the old commit that broke Nvidia pro support:
[old_mpvpaper.zip](https://github.com/GhostNaN/mpvpaper/files/15079018/old_mpvpaper.zip)

And let me know what happens. Thanks.

**Comment by Rodrigo-Matuz** [comment]
Removed mpvpaper and mpvpaper-holder from binaries manually just in case

build the project with 
`meson setup build --prefix=/user/local & ninja -C build`
![image](https://github.com/GhostNaN/mpvpaper/assets/109036200/35704885-bee1-4f1a-a7fe-a06a44a7901d)
[output.txt](https://github.com/GhostNaN/mpvpaper/files/15079418/output.txt)

**Comment by Rodrigo-Matuz** [comment]
as for your suggestion, it works perfectly 
![image](https://github.com/GhostNaN/mpvpaper/assets/109036200/ce11d1ce-cb25-428d-8688-d44bddbd6575)

**Comment by GhostNaN** [comment]
Wait. So the "old_mpvpaper.zip" worked?

**Comment by Rodrigo-Matuz** [comment]
> Wait. So the "old_mpvpaper.zip" worked?

No, the old_mpvpaper.zip is above

what worked for me was your comment reffering to that branch https://github.com/GhostNaN/mpvpaper/commit/f65700a3ecc9ecd8ca501e18a807ee18845f9441 
> For now you could use that old commit but just set the VO manually to "libmpv" like so:
> mpvpaper -o "--vo=libmpv" HDMI-A-1 ~/Pictures/wallpaper.mp4

**Comment by Rodrigo-Matuz** [comment]
Still black screen, heres the log: 
[output.txt](https://github.com/GhostNaN/mpvpaper/files/15079619/output.txt)



![image](https://github.com/GhostNaN/mpvpaper/assets/109036200/f3e93c79-499e-4f04-8f43-23f0fc86e65b)

**Comment by GhostNaN** [comment]
Dammit, so close...
I hate this black box crap.

I appreciate the effort.

**Comment by Rodrigo-Matuz** [comment]
> Dammit, so close... I hate this black box crap.
> 
> I appreciate the effort.

All good, let me know if I can help in testing, don't mind at all :D

Thanks to you I can now have my animated waifu on my desktop.

**Comment by GhostNaN** [comment]
By some miracle I remembered I had an old work laptop that has a crappy "Quadro P1000".
And after countless wasted hours with the Nvidia pro driver, I was able to find some fixes.

Please try the latest commits and compile from master.
Then let me know if I can finally rest this issue.

**Comment by Rodrigo-Matuz** [comment]
It works! [output.txt](https://github.com/GhostNaN/mpvpaper/files/15103340/output.txt)

![image](https://github.com/GhostNaN/mpvpaper/assets/109036200/5c975898-ca33-4f32-a7b5-d21236b0acf3)

**Comment by GhostNaN** [comment]
After 2 years it's finally over...
I'll let the others know.

**Comment by GhostNaN** [comment]
Wait. It seems it's still getting stuck.
I see a bunch of "mpv_render_context_render() not being called or stuck." errors.
Make sure it's running smoothly.

**Comment by Rodrigo-Matuz** [comment]
GPU usage around the same with some stuttering but not that much 

https://youtu.be/8MOzcef-aa8

**Comment by GhostNaN** [comment]
> GPU usage around the same with some stuttering but not that much

No, it's a real issue.
I was able to replicate it by speeding up the video.
I found a workaround for this issue, but it's more of a hack than a proper fix.
I'll let you know if I need more help.

**Comment by GhostNaN** [comment]
Go ahead and try again.
It should be flawless.

**Comment by Rodrigo-Matuz** [comment]
Awesome, no stuttering for sure.
[output.txt](https://github.com/GhostNaN/mpvpaper/files/15122383/output.txt)
