### ISSUE TITLE
request: similar tool that allows any program to be used as desktop background

### ISSUE THREAD

**Issue by DaeTheDragon** [GhostNaN/mpvpaper#72]
Hiya! this is really great!
I don't know if this would be possible, but if it were it'd be wonderful if you could choose what program to use as the desktop background, instead of MPV being the only option
I don't have much of an idea of what I'm doing myself, but I really want to have something similar to this but using qutebrowser instead of MPV so that I can have an interactive webpage as my desktop background!
is there any way of doing this? 
any advice on this would be appreciated <3
I'm using Sway!

Thanks!

- Dae

**Comment by GhostNaN** [comment]
> I don't know if this would be possible

It's possible sure, but it's also WAY outside the scope of this project.
And I don't really have the motivation myself to make a new project that could implement this.
I imagine it could involve with using Pipewire to "screen share" to a Wayland surface.
Otherwise, I really don't have a clue how this could be done.

> any advice on this would be appreciated

If you want you could get your hands dirty and perhaps code this yourself.
When I made mpvpaper I used some code from [swaybg](https://github.com/swaywm/swaybg) and [glpaper](https://hg.sr.ht/~scoopta/glpaper) as a starting point.
Then I read the [wayland book](https://wayland-book.com/introduction.html) to get a better understanding of what I was working with.

With all that said, I'm closing the issue.
As I don't plan on implementing or integrating this functionality into mpvpaper.
I wish you all the luck.
