### ISSUE TITLE
stopping cause mpvpaper is hidden

### ISSUE THREAD

**Issue by v1ncenz0graw** [GhostNaN/mpvpaper#74]
OS: Fedora 40
Device: Asus ROG Strix g16 (2023)
GPU: NVIDIA 4060 8gb
CPU: Core i7
Issue:
` mpvpaper -f -o "no-audio loop" "*" ~/Desktop/toyota.mp4 ` 
video runs for several times and freezes.
then tried with ` mpvpaper -vs -o "no-audio loop" "*" ~/Desktop/toyota.mp4 `
and in the log, it says "stopping cause mpvpaper is hidden". even if i don't activate any app yet

How can i prevent mpvpaper to go hidden?

**Comment by GhostNaN** [comment]
2 things

1. Did you compile and run from the latest commit?
As I feel like this issue is from the fact the old build would drop frames on NVIDIA GPUs.

2. Read the man page.
If you don't feel like reading the man page ```-s``` means stop automatically if mpvpaper is hidden.
Like behind a fullscreen window.
If you don't care for that feature or think it doesn't work on your WM (which is possible as it's just a hack)
You can just add your programs that shows with ```pidof``` at ```~/.config/mpvpaper/stoplist```

**Comment by v1ncenz0graw** [comment]
> 2 things
> 
>     1. Did you compile and run from the latest commit?
>        As I feel like this issue is from the fact the old build would drop frames on NVIDIA GPUs.
> 
>     2. Read the man page.
>        If you don't feel like reading the man page `-s` means stop automatically if mpvpaper is hidden.
>        Like behind a fullscreen window.
>        If you don't care for that feature or think it doesn't work on your WM (which is possible as it's just a hack)
>        You can just add your programs that shows with `pidof` at `~/.config/mpvpaper/stoplist`


Thanks, it is working now

**Comment by GhostNaN** [comment]
I made a new stable release of mpvpaper so this should not come up again.
