### ISSUE TITLE
Ways to force use iGPU instead of dGPU

### ISSUE THREAD

**Issue by So1aric** [GhostNaN/mpvpaper#75]
I'm on Arch, official 'nvidia' driver.
See the motivation: https://github.com/hyprwm/Hyprland/discussions/7035

I test for mpv, and it won't block the card from turning off. But after executing mpvpaper, the card was turned on.

So if it's caused by mpvpaper, is there a way to force mpvpaper only use cpu/iGPU instead of dGPU?

**Comment by GhostNaN** [comment]
mpvpaper doesn't select a GPU here.
That's up to OpenGL and mpv.

But if you started Hyprland with the IGPU, most likely your IGPU will be used for mpvpaper.
I tested on my own laptop and confirmed with ```nvtop``` that is the case.
You can test this yourself and see which "DEV" or device is being used in ```nvtop```
In fact, you could force the gGPU to be used with ```prime-run``` and see the "DEV" change.

If you still see mpvpaper using your dGPU without ```prime-run```
I would double check your ENV and your mpv options and configs.

> I saw mpvpaper depend on cuda in some versions

No, it does not.
There is no cuda code at all.
```mpv``` on the other hand will try to use cuda if compiled for it and available. 
Otherwise, it will show ```Cannot load libcuda.so.1```, which is harmless.

**Comment by So1aric** [comment]
Yes you are right, mpvpaper is running at the iGPU.
But it does block the dGPU from turning off. Quite strange here.
